//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public decimal Amount { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string About { get; set; }
        public Nullable<int> Scheduled { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public int TransactionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Recurring { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TransactionType { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual Category Category { get; set; }
        public virtual TransactionType TransactionType1 { get; set; }
        public virtual User User { get; set; }
    }
}
